services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2
    networks:
      subnet_1:
        ipv4_address: 172.20.1.3
      subnet_2:
        ipv4_address: 172.20.2.4
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1,router3
    networks:
      subnet_2:
        ipv4_address: 172.20.2.3
      subnet_1:
        ipv4_address: 172.20.1.2
      subnet_3:
        ipv4_address: 172.20.3.4
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2,router4
    networks:
      subnet_3:
        ipv4_address: 172.20.3.3
      subnet_2:
        ipv4_address: 172.20.2.2
      subnet_4:
        ipv4_address: 172.20.4.4
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router3,router5
    networks:
      subnet_4:
        ipv4_address: 172.20.4.3
      subnet_3:
        ipv4_address: 172.20.3.2
      subnet_5:
        ipv4_address: 172.20.5.4
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router4,router6
    networks:
      subnet_5:
        ipv4_address: 172.20.5.3
      subnet_4:
        ipv4_address: 172.20.4.2
      subnet_6:
        ipv4_address: 172.20.6.4
  router6:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router5,router7
    networks:
      subnet_6:
        ipv4_address: 172.20.6.3
      subnet_5:
        ipv4_address: 172.20.5.2
      subnet_7:
        ipv4_address: 172.20.7.4
  router7:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router6,router8
    networks:
      subnet_7:
        ipv4_address: 172.20.7.3
      subnet_6:
        ipv4_address: 172.20.6.2
      subnet_8:
        ipv4_address: 172.20.8.4
  router8:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router7,router9
    networks:
      subnet_8:
        ipv4_address: 172.20.8.3
      subnet_7:
        ipv4_address: 172.20.7.2
      subnet_9:
        ipv4_address: 172.20.9.4
  router9:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router8,router10
    networks:
      subnet_9:
        ipv4_address: 172.20.9.3
      subnet_8:
        ipv4_address: 172.20.8.2
      subnet_10:
        ipv4_address: 172.20.10.4
  router10:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router9
    networks:
      subnet_10:
        ipv4_address: 172.20.10.3
      subnet_9:
        ipv4_address: 172.20.9.2
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
  subnet_6:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.6.0/24
  subnet_7:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.7.0/24
  subnet_8:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.8.0/24
  subnet_9:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.9.0/24
  subnet_10:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.10.0/24
