services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2
    networks:
      subnet_1:
        ipv4_address: 172.20.1.3
      subnet_2:
        ipv4_address: 172.20.2.4
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1,router3
    networks:
      subnet_2:
        ipv4_address: 172.20.2.3
      subnet_1:
        ipv4_address: 172.20.1.2
      subnet_3:
        ipv4_address: 172.20.3.4
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2,router4
    networks:
      subnet_3:
        ipv4_address: 172.20.3.3
      subnet_2:
        ipv4_address: 172.20.2.2
      subnet_4:
        ipv4_address: 172.20.4.4
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router3,router5
    networks:
      subnet_4:
        ipv4_address: 172.20.4.3
      subnet_3:
        ipv4_address: 172.20.3.2
      subnet_5:
        ipv4_address: 172.20.5.4
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router4
    networks:
      subnet_5:
        ipv4_address: 172.20.5.3
      subnet_4:
        ipv4_address: 172.20.4.2
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
