services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2
    - my_ip=172.20.1.3
    - my_name=router1
    networks:
      subnet_1:
        ipv4_address: 172.20.1.3
      subnet_2:
        ipv4_address: 172.20.2.4
    cap_add:
    - NET_ADMIN
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router1,router3
    - my_ip=172.20.2.3
    - my_name=router2
    networks:
      subnet_2:
        ipv4_address: 172.20.2.3
      subnet_1:
        ipv4_address: 172.20.1.2
      subnet_3:
        ipv4_address: 172.20.3.4
    cap_add:
    - NET_ADMIN
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router2,router4
    - my_ip=172.20.3.3
    - my_name=router3
    networks:
      subnet_3:
        ipv4_address: 172.20.3.3
      subnet_2:
        ipv4_address: 172.20.2.2
      subnet_4:
        ipv4_address: 172.20.4.4
    cap_add:
    - NET_ADMIN
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router3,router5
    - my_ip=172.20.4.3
    - my_name=router4
    networks:
      subnet_4:
        ipv4_address: 172.20.4.3
      subnet_3:
        ipv4_address: 172.20.3.2
      subnet_5:
        ipv4_address: 172.20.5.4
    cap_add:
    - NET_ADMIN
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router4,router6
    - my_ip=172.20.5.3
    - my_name=router5
    networks:
      subnet_5:
        ipv4_address: 172.20.5.3
      subnet_4:
        ipv4_address: 172.20.4.2
      subnet_6:
        ipv4_address: 172.20.6.4
    cap_add:
    - NET_ADMIN
  router6:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router5,router7
    - my_ip=172.20.6.3
    - my_name=router6
    networks:
      subnet_6:
        ipv4_address: 172.20.6.3
      subnet_5:
        ipv4_address: 172.20.5.2
      subnet_7:
        ipv4_address: 172.20.7.4
    cap_add:
    - NET_ADMIN
  router7:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router6,router8
    - my_ip=172.20.7.3
    - my_name=router7
    networks:
      subnet_7:
        ipv4_address: 172.20.7.3
      subnet_6:
        ipv4_address: 172.20.6.2
      subnet_8:
        ipv4_address: 172.20.8.4
    cap_add:
    - NET_ADMIN
  router8:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router7,router9
    - my_ip=172.20.8.3
    - my_name=router8
    networks:
      subnet_8:
        ipv4_address: 172.20.8.3
      subnet_7:
        ipv4_address: 172.20.7.2
      subnet_9:
        ipv4_address: 172.20.9.4
    cap_add:
    - NET_ADMIN
  router9:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router8,router10
    - my_ip=172.20.9.3
    - my_name=router9
    networks:
      subnet_9:
        ipv4_address: 172.20.9.3
      subnet_8:
        ipv4_address: 172.20.8.2
      subnet_10:
        ipv4_address: 172.20.10.4
    cap_add:
    - NET_ADMIN
  router10:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - router_links=router9
    - my_ip=172.20.10.3
    - my_name=router10
    networks:
      subnet_10:
        ipv4_address: 172.20.10.3
      subnet_9:
        ipv4_address: 172.20.9.2
    cap_add:
    - NET_ADMIN
  host1a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.10
    depends_on:
    - router1
  host1b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_1:
        ipv4_address: 172.20.1.11
    depends_on:
    - router1
  host2a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.10
    depends_on:
    - router2
  host2b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_2:
        ipv4_address: 172.20.2.11
    depends_on:
    - router2
  host3a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.10
    depends_on:
    - router3
  host3b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_3:
        ipv4_address: 172.20.3.11
    depends_on:
    - router3
  host4a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.10
    depends_on:
    - router4
  host4b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_4:
        ipv4_address: 172.20.4.11
    depends_on:
    - router4
  host5a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.10
    depends_on:
    - router5
  host5b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_5:
        ipv4_address: 172.20.5.11
    depends_on:
    - router5
  host6a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_6:
        ipv4_address: 172.20.6.10
    depends_on:
    - router6
  host6b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_6:
        ipv4_address: 172.20.6.11
    depends_on:
    - router6
  host7a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_7:
        ipv4_address: 172.20.7.10
    depends_on:
    - router7
  host7b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_7:
        ipv4_address: 172.20.7.11
    depends_on:
    - router7
  host8a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_8:
        ipv4_address: 172.20.8.10
    depends_on:
    - router8
  host8b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_8:
        ipv4_address: 172.20.8.11
    depends_on:
    - router8
  host9a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_9:
        ipv4_address: 172.20.9.10
    depends_on:
    - router9
  host9b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_9:
        ipv4_address: 172.20.9.11
    depends_on:
    - router9
  host10a:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_10:
        ipv4_address: 172.20.10.10
    depends_on:
    - router10
  host10b:
    build:
      context: ./host
      dockerfile: Dockerfile
    networks:
      subnet_10:
        ipv4_address: 172.20.10.11
    depends_on:
    - router10
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
  subnet_6:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.6.0/24
  subnet_7:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.7.0/24
  subnet_8:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.8.0/24
  subnet_9:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.9.0/24
  subnet_10:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.10.0/24
