services:
  router1:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - vizinhos=[router2, 172.20.2.3, 1]
    - my_ip=172.20.1.3
    - my_name=router1
    networks:
      subnet_2:
        ipv4_address: 172.20.2.4
      subnet_1:
        ipv4_address: 172.20.1.3
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route del default && ip route add default via 172.20.1.1
      && python router.py"
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - vizinhos=[router1, 172.20.1.3, 1],[router3, 172.20.3.3, 1]
    - my_ip=172.20.2.3
    - my_name=router2
    networks:
      subnet_1:
        ipv4_address: 172.20.1.2
      subnet_3:
        ipv4_address: 172.20.3.4
      subnet_2:
        ipv4_address: 172.20.2.3
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route del default && ip route add default via 172.20.2.1
      && python router.py"
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - vizinhos=[router2, 172.20.2.3, 1],[router4, 172.20.4.3, 1]
    - my_ip=172.20.3.3
    - my_name=router3
    networks:
      subnet_2:
        ipv4_address: 172.20.2.2
      subnet_4:
        ipv4_address: 172.20.4.4
      subnet_3:
        ipv4_address: 172.20.3.3
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route del default && ip route add default via 172.20.3.1
      && python router.py"
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - vizinhos=[router3, 172.20.3.3, 1],[router5, 172.20.5.3, 1]
    - my_ip=172.20.4.3
    - my_name=router4
    networks:
      subnet_3:
        ipv4_address: 172.20.3.2
      subnet_5:
        ipv4_address: 172.20.5.4
      subnet_4:
        ipv4_address: 172.20.4.3
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route del default && ip route add default via 172.20.4.1
      && python router.py"
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    environment:
    - vizinhos=[router4, 172.20.4.3, 1]
    - my_ip=172.20.5.3
    - my_name=router5
    networks:
      subnet_4:
        ipv4_address: 172.20.4.2
      subnet_5:
        ipv4_address: 172.20.5.3
    cap_add:
    - NET_ADMIN
    command: /bin/bash -c "ip route del default && ip route add default via 172.20.5.1
      && python router.py"
networks:
  subnet_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
        gateway: 172.20.1.1
  subnet_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
        gateway: 172.20.2.1
  subnet_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
        gateway: 172.20.3.1
  subnet_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
        gateway: 172.20.4.1
  subnet_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
        gateway: 172.20.5.1
